# Generated by Django 2.1 on 2020-01-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ('owner',)},
        ),
    ]
